### ISSUE TITLE
Having to press Enter each time i load the program.

### ISSUE THREAD

**Issue by Gaffers2277** [swetoast/steamlink-launcher#53] opened 2022-10-17 18:52 UTC
I have it working and its been great but i do have a bit of an issue as i have to press enter on a keyboard each time i load this program on my raspberry pi 4b 8gb running OSMC 2022.09-1. I obviously dont really want to keep a keyboard plugged in all time just to do this once button press. Can i fix this? It also says i should probably change the vram from 128mbs but i think the raspberry pi 4b has dynamic allocation for vram from my research.

**Comment by swetoast** [comment] 2022-10-17 18:55
logs please

**Comment by jose1711** [comment] 2022-10-21 21:49
Same here with RPi3 B+. With OSMC's default:
```
dtoverlay=vc4-kms-v3d,cma-512
```
`vcgencmd get_mem gpu` reports the following:
```
gpu=76M
```
and `steamlink.sh` does not seem to like that:
```
..
# Check to make sure there's enough GPU memory
if [ ! -f "$TOP/.ignore_gpumem" ]; then
  mem=$(vcgencmd get_mem gpu | sed 's/.*=\([0-9]*\)M/\1/')
  if [ "$mem" = "" ] || [ "$mem" -lt 128 ]; then
    show_message --warning $"You are running with less than 128 MB video memory, you may need to go to the Raspberry Pi Configuration and increase your GPU memory."
```
Not sure with CMA if GPU mem is still a thing or this warning could be removed altogether.

**Comment by jose1711** [comment] 2022-10-21 21:53
@Gaffers2277 As a workaround you might as well run:
```
touch /home/osmc/.local/share/SteamLink/.ignore_gpumem
```
from the terminal. That disables the check.

**Comment by chepe263** [comment] 2022-10-24 06:28
Does setting `gpu_mem` in the [boot config](https://www.raspberrypi.com/documentation/computers/config_txt.html#gpu_mem) make a positive change?

**Comment by swetoast** [comment] 2022-10-24 15:03
hey guys great find ill try and make time for it or if someone is up for making a patch and merge it

**Comment by StoneAgeSkillz** [comment] 2023-01-10 13:42
Same issue with my RPi4 (4GB), changing gpu_mem does not help. If i set gpu_mem to 512, OSMC will start (i can connect to SSH), but has no video output (no HDMI signal at all). Disabling check helped to skip the memory error and it works, but ignoring issues is not what i want.

**Comment by swetoast** [comment] 2023-01-22 06:37
Mind testing this fork ? 

https://github.com/cwildfoerster/steamlink-launcher

**Comment by swetoast** [comment] 2024-12-10 06:04
dupe of 61, closing

**Closed by swetoast** 2024-12-10 06:04 UTC
